/* Tech Quiz — multiple-choice quizzes with explanations.
 * Pure client-side, no dependencies. */

const LLM_QUIZZES = {
  generic: {
    title: "Generic Language Models",
    icon: "G",
    description: "Foundation models trained on broad text to predict the next token.",
    questions: [
      {
        q: "What is the core training objective of a generic (pretrained) large language model?",
        choices: [
          "Maximize a human-rating score from labelers",
          "Predict the next token given the previous tokens",
          "Classify text into predefined categories",
          "Translate text between two specified languages"
        ],
        answer: 1,
        explanation: "Generic LLMs are trained with self-supervised next-token prediction on huge corpora. No human labels or task-specific heads are needed — the model just learns to continue text, which implicitly forces it to learn grammar, facts, and reasoning patterns."
      },
      {
        q: "Why are generic LLMs sometimes called 'foundation models'?",
        choices: [
          "They run only on foundational hardware like CPUs",
          "They form a general-purpose base that can be adapted to many downstream tasks",
          "They were the first models ever built",
          "They are limited to one foundational task such as translation"
        ],
        answer: 1,
        explanation: "Coined by Stanford's CRFM in 2021, 'foundation model' captures the idea that one large pretrained model serves as a base that can be fine-tuned, prompted, or adapted to a wide variety of tasks — rather than training a separate model from scratch for each task."
      },
      {
        q: "If you ask a purely generic (not instruction-tuned) language model 'What is the capital of France?', what is the most likely behavior?",
        choices: [
          "It refuses because it is not allowed to answer questions",
          "It answers concisely with 'Paris.'",
          "It may continue the text — e.g., generate more questions or a quiz-like list rather than directly answering",
          "It returns an error because the prompt is not well-formed"
        ],
        answer: 2,
        explanation: "A pure pretrained LLM is just a text continuator. Without instruction tuning, it has no special bias to 'follow' a question — it predicts what text typically follows. Often this means continuing in the same style, e.g., listing more trivia questions, rather than answering directly."
      },
      {
        q: "Which of the following is NOT typically a property of generic pretrained LLMs?",
        choices: [
          "Trained with self-supervised learning on unlabeled text",
          "Capable of few-shot in-context learning",
          "Aligned by default to be helpful, harmless, and honest",
          "Knowledge is bounded by their training cutoff"
        ],
        answer: 2,
        explanation: "Alignment (helpful/harmless/honest) is added on top of pretraining via instruction tuning and RLHF/RLAIF. A purely pretrained model has no built-in notion of being helpful — that property comes from later post-training stages."
      },
      {
        q: "Which dataset characteristic is most typical for pretraining a generic LLM?",
        choices: [
          "A small, hand-curated dataset of question/answer pairs",
          "A massive, diverse corpus of unlabeled text from the web, books, and code",
          "A labeled dataset of dialogues with human ratings",
          "Synthetic data generated by another aligned model"
        ],
        answer: 1,
        explanation: "Pretraining relies on scale and diversity — trillions of tokens drawn from web crawls, books, code, and other sources. The text is unlabeled; the next-token target comes for free from the data itself."
      }
    ]
  },

  instruction: {
    title: "Instruction-Tuned LLMs",
    icon: "I",
    description: "Models fine-tuned to follow natural-language instructions.",
    questions: [
      {
        q: "What is the main goal of instruction tuning?",
        choices: [
          "To make a model run faster at inference time",
          "To shrink the model so it fits on smaller hardware",
          "To teach the model to follow natural-language instructions across many tasks",
          "To make the model memorize a specific knowledge base"
        ],
        answer: 2,
        explanation: "Instruction tuning fine-tunes a pretrained model on a curated dataset of (instruction, response) pairs across many task types. The result is a model that interprets requests like 'Summarize this' or 'Translate to French' even on task descriptions it has never seen verbatim."
      },
      {
        q: "Which of these is a well-known instruction-tuning dataset / approach?",
        choices: [
          "FLAN / Super-NaturalInstructions",
          "ImageNet",
          "WMT Newstest",
          "GLUE"
        ],
        answer: 0,
        explanation: "FLAN (Google) and Super-NaturalInstructions (AI2) collected hundreds to thousands of NLP tasks rephrased as natural-language instructions. Fine-tuning on them dramatically improved zero-shot generalization. The other options are evaluation/benchmark datasets, not instruction-tuning corpora."
      },
      {
        q: "InstructGPT, the instruction-tuned predecessor of ChatGPT, was trained using which two-stage post-training recipe?",
        choices: [
          "Distillation followed by quantization",
          "Supervised fine-tuning on demonstrations, followed by RLHF",
          "Adversarial training followed by pruning",
          "Continued pretraining followed by curriculum learning"
        ],
        answer: 1,
        explanation: "OpenAI's InstructGPT paper (Ouyang et al., 2022) introduced the SFT + RLHF recipe: first fine-tune on human-written demonstrations, then train a reward model from human preferences and optimize the LLM against it with PPO."
      },
      {
        q: "Compared to a base GPT-3 model, InstructGPT (1.3B parameters) was preferred by human raters over the much larger 175B base model. What does this primarily demonstrate?",
        choices: [
          "Smaller models are always better",
          "Alignment via instruction tuning can outweigh raw parameter count for usefulness",
          "RLHF is unnecessary",
          "Pretraining data quality does not matter"
        ],
        answer: 1,
        explanation: "The InstructGPT result is a landmark demonstration that *alignment* — teaching a model to follow intent — adds far more practical usefulness than scaling alone. A 1.3B aligned model beat 175B base GPT-3 in human preference, even though the larger model knew more facts."
      },
      {
        q: "Which statement about instruction-tuned models is most accurate?",
        choices: [
          "They no longer need a pretrained base model",
          "They can only handle tasks seen during fine-tuning",
          "They generally generalize zero-shot to unseen instructions, but can still hallucinate",
          "They are guaranteed to be factually correct"
        ],
        answer: 2,
        explanation: "Instruction tuning gives strong zero-shot generalization to unseen tasks because the model learns the *format* of following instructions. But it does not fix factual reliability — instruction-tuned models still hallucinate, and they always start from a pretrained base."
      }
    ]
  },

  dialogue: {
    title: "Dialogue-Tuned LLMs",
    icon: "D",
    description: "Models specialized for multi-turn conversation and chat.",
    questions: [
      {
        q: "What primarily distinguishes a dialogue-tuned LLM from an instruction-tuned LLM?",
        choices: [
          "It has more parameters",
          "It is optimized for multi-turn conversation, with awareness of speaker roles and chat history",
          "It only works in English",
          "It cannot follow instructions"
        ],
        answer: 1,
        explanation: "Dialogue tuning builds on instruction tuning but adds multi-turn structure: distinct system/user/assistant roles, persistent context across turns, and conversational behaviors like asking clarifying questions, maintaining persona, and avoiding repetition."
      },
      {
        q: "What is RLHF (Reinforcement Learning from Human Feedback) most commonly used for in dialogue models like ChatGPT and Claude?",
        choices: [
          "Compressing the model to fit on a phone",
          "Aligning the model's outputs with human preferences for helpfulness, harmlessness, and tone",
          "Speeding up token generation",
          "Eliminating the need for any training data"
        ],
        answer: 1,
        explanation: "RLHF trains a reward model on human preference comparisons, then uses RL (typically PPO) to push the LLM toward responses humans prefer. In chat models this is the main mechanism for making replies feel helpful, honest, and safe — beyond what supervised fine-tuning alone can achieve."
      },
      {
        q: "Which of these is the typical message-role structure used in dialogue-tuned LLM APIs?",
        choices: [
          "input / output / metadata",
          "prompt / completion only",
          "system / user / assistant",
          "encoder / decoder / classifier"
        ],
        answer: 2,
        explanation: "Modern chat APIs (OpenAI, Anthropic, etc.) standardize on system/user/assistant roles. The system message sets persona and rules, user messages are the human's turns, and assistant messages are the model's prior replies. The model is fine-tuned to respect these role boundaries."
      },
      {
        q: "Which of these problems is dialogue tuning specifically designed to address?",
        choices: [
          "Models forgetting earlier turns or breaking persona within a conversation",
          "Slow GPU kernels",
          "Tokenization errors",
          "The need for vector databases"
        ],
        answer: 0,
        explanation: "Multi-turn coherence is a defining challenge for chat models: keeping track of what was said earlier, sticking to a persona/system instructions, and producing replies that fit the conversational flow. Dialogue tuning explicitly trains on multi-turn data to improve this."
      },
      {
        q: "Anthropic's Constitutional AI (CAI) is best described as:",
        choices: [
          "A new tokenization scheme",
          "An alternative to RLHF where the model critiques and revises its own outputs based on a set of principles",
          "A regulatory framework imposed by governments",
          "A way to prune model weights"
        ],
        answer: 1,
        explanation: "Constitutional AI (Bai et al., 2022) replaces much of the human preference labeling in RLHF with AI feedback guided by a written 'constitution' of principles. The model critiques and revises its own outputs, and a reward model is trained from those AI-generated preferences (RLAIF)."
      }
    ]
  },

  domain: {
    title: "Domain-Specific LLMs",
    icon: "S",
    description: "Models specialized for medicine, law, code, finance, and more.",
    questions: [
      {
        q: "Which of these is an example of a domain-specific LLM?",
        choices: [
          "GPT-4",
          "Med-PaLM (medical) or BloombergGPT (finance)",
          "BERT-base",
          "Llama 3 base"
        ],
        answer: 1,
        explanation: "Med-PaLM (Google) is tuned for medical question answering; BloombergGPT was pretrained on a finance-heavy corpus for financial NLP. The other options are general-purpose models. Other domain examples include Codex (code), SciBERT (science), and Legal-BERT (law)."
      },
      {
        q: "What are the two most common ways to build a domain-specific LLM?",
        choices: [
          "Increasing the temperature and top-p",
          "Continued pretraining / fine-tuning on domain text, or retrieval-augmented generation (RAG)",
          "Quantizing weights to int4",
          "Replacing the tokenizer with whitespace splitting"
        ],
        answer: 1,
        explanation: "You either bake domain knowledge into the weights — by continued pretraining or fine-tuning on domain corpora — or you keep a generic model and supply domain knowledge at inference time via retrieval (RAG). In practice, hybrid approaches (fine-tune + RAG) are common."
      },
      {
        q: "Which is a key advantage of a well-built domain-specific LLM over a general-purpose LLM?",
        choices: [
          "It is always smaller and cheaper, regardless of task",
          "It tends to use domain vocabulary correctly and produces more reliable answers within its domain",
          "It eliminates hallucinations entirely",
          "It removes the need for evaluation"
        ],
        answer: 1,
        explanation: "Domain models internalize specialist terminology, conventions, and reasoning patterns (e.g., ICD codes, legal citation styles, financial jargon). They are usually more accurate and fluent within their domain — but they can still hallucinate and they don't necessarily save compute."
      },
      {
        q: "Codex / Code Llama / StarCoder are domain-specific LLMs for which domain?",
        choices: [
          "Medicine",
          "Law",
          "Source code",
          "Finance"
        ],
        answer: 2,
        explanation: "These are code-specialized LLMs, typically pretrained or continue-pretrained on large public code corpora (e.g., The Stack, GitHub). Code is one of the clearest success stories for domain specialization — code-tuned models handily beat general models at programming tasks of similar size."
      },
      {
        q: "When is Retrieval-Augmented Generation (RAG) often preferred over fine-tuning a domain-specific LLM?",
        choices: [
          "When the domain knowledge changes frequently or must be auditable / citable",
          "When you want the model to be smaller",
          "When you have unlimited GPUs",
          "When you don't care about correctness"
        ],
        answer: 0,
        explanation: "RAG keeps knowledge in an external store you can update without retraining, and it lets you cite sources — both critical when facts change often (news, policies, product docs) or when answers must be verifiable (medicine, law). Fine-tuning bakes knowledge into weights, which is harder to update or audit."
      }
    ]
  },

  evolution: {
    title: "Evolution of LLMs",
    icon: "E",
    description: "From n-grams and word embeddings to transformers and modern frontier models.",
    questions: [
      {
        q: "Which 2017 paper introduced the architecture that underpins essentially all modern large language models?",
        choices: [
          "'Sequence to Sequence Learning with Neural Networks' (Sutskever et al., 2014)",
          "'Attention Is All You Need' (Vaswani et al., 2017)",
          "'Deep Residual Learning for Image Recognition' (He et al., 2015)",
          "'Generative Adversarial Networks' (Goodfellow et al., 2014)"
        ],
        answer: 1,
        explanation: "'Attention Is All You Need' introduced the Transformer architecture, replacing recurrence with self-attention. It enabled massive parallel training and became the substrate for BERT, GPT, T5, and every major LLM since."
      },
      {
        q: "Roughly chronologically, which ordering reflects the evolution of language modeling?",
        choices: [
          "Transformers → n-gram models → RNN/LSTM → word2vec",
          "n-gram models → word2vec/GloVe → RNN/LSTM → Transformers (BERT/GPT) → modern LLMs",
          "BERT → n-gram → GPT-4 → word2vec",
          "GPT-4 → LSTM → n-gram → BERT"
        ],
        answer: 1,
        explanation: "The rough trajectory: statistical n-gram models (pre-2010s) → distributed word embeddings like word2vec/GloVe (2013–14) → recurrent encoder-decoders with attention (LSTMs, ~2014–17) → Transformers and pretrained models like BERT/GPT (2018+) → today's frontier LLMs."
      },
      {
        q: "What was the key insight of BERT (2018) versus prior approaches?",
        choices: [
          "Replacing transformers with LSTMs",
          "Using a left-to-right autoregressive objective",
          "Bidirectional masked-language-model pretraining followed by fine-tuning on downstream tasks",
          "Training only on labeled data"
        ],
        answer: 2,
        explanation: "BERT pretrained a Transformer encoder with masked language modeling (predict missing tokens using both left and right context) plus next-sentence prediction, then fine-tuned a small head per task. It set new SOTA across NLP and popularized the 'pretrain + fine-tune' paradigm."
      },
      {
        q: "Which capability was popularized by GPT-3 (2020) and is largely a consequence of scale?",
        choices: [
          "Image generation",
          "In-context (few-shot) learning — solving new tasks from a few examples in the prompt, with no weight updates",
          "Reinforcement learning",
          "Speech synthesis"
        ],
        answer: 1,
        explanation: "GPT-3 showed that at sufficient scale, a single autoregressive model could perform new tasks from a handful of examples in the prompt (in-context / few-shot learning). This capability emerged with scale and reframed how people use LLMs — via prompting rather than fine-tuning."
      },
      {
        q: "Scaling laws (Kaplan et al., 2020; Hoffmann et al., 2022 'Chinchilla') describe how loss scales with which factors?",
        choices: [
          "Only the number of parameters",
          "Model size, dataset size, and compute — and how to balance them",
          "GPU brand and operating system",
          "Number of attention heads only"
        ],
        answer: 1,
        explanation: "Kaplan et al. found smooth power-law relationships between loss and parameters/data/compute. Chinchilla (DeepMind, 2022) corrected the recipe: for a fixed compute budget you should train smaller models on much more data than was previously typical — model and data should scale together."
      },
      {
        q: "Which milestone marked LLMs becoming a mainstream consumer product?",
        choices: [
          "The release of word2vec (2013)",
          "The release of BERT (2018)",
          "The launch of ChatGPT (November 2022)",
          "The publication of the Transformer paper (2017)"
        ],
        answer: 2,
        explanation: "ChatGPT's launch in late 2022 took LLMs from a research/developer tool to a household product, reaching 100M users within ~2 months. It also accelerated investment, multimodal extensions, agentic use cases, and the broader 'LLM era' of AI."
      },
      {
        q: "Which trend characterizes frontier LLMs from ~2023 onward?",
        choices: [
          "A return to recurrent neural networks",
          "Multimodality (text + images + audio), longer context windows, tool use, and explicit reasoning models",
          "Abandoning transformers entirely for symbolic AI",
          "Pure unsupervised training with no post-training"
        ],
        answer: 1,
        explanation: "Recent frontier LLMs (GPT-4o, Claude 3/4, Gemini, Llama 3+) extend the transformer recipe with multimodal inputs/outputs, much longer context (100K–1M+ tokens), native tool/function calling, and explicit 'thinking' / reasoning modes. The transformer backbone has stayed; the surrounding capabilities have exploded."
      }
    ]
  }
};

const GPU_QUIZZES = {
  architecture: {
    title: "GPU Architecture",
    icon: "A",
    description: "Cores, warps, memory hierarchy, and the SIMT execution model.",
    questions: [
      {
        q: "Which execution model best describes how modern NVIDIA GPUs run code?",
        choices: [
          "MIMD — every core fetches a different instruction per cycle",
          "SIMT — groups of threads execute the same instruction together in lock-step",
          "Pure scalar execution, one instruction per thread per cycle, fully independent",
          "Dataflow — instructions fire when their inputs are ready"
        ],
        answer: 1,
        explanation: "NVIDIA calls its model SIMT (Single Instruction, Multiple Threads). Threads are grouped into warps of 32 that share an instruction pointer; if threads in a warp take different branches, the warp serializes them (warp divergence). It's a generalization of classic SIMD."
      },
      {
        q: "On NVIDIA GPUs, how many threads make up a single warp?",
        choices: ["8", "16", "32", "64"],
        answer: 2,
        explanation: "An NVIDIA warp is 32 threads. AMD's analogous unit is the wavefront — historically 64 threads on GCN, and 32 on RDNA. Warp/wavefront size matters because divergent branches inside one warp serialize and waste lanes."
      },
      {
        q: "Which is the typical memory hierarchy ordering on a GPU, from fastest to slowest?",
        choices: [
          "Global memory → L2 cache → shared memory → registers",
          "Registers → shared memory / L1 → L2 cache → global (HBM/GDDR) memory",
          "HBM → registers → shared memory → L2",
          "L2 → registers → L1 → shared memory"
        ],
        answer: 1,
        explanation: "From fastest/smallest to slowest/largest: per-thread registers, then per-block shared memory / L1 (on-chip SRAM), then a shared L2 cache, then off-chip global memory (GDDR or HBM). Good GPU code keeps hot data in registers and shared memory."
      },
      {
        q: "What is a Streaming Multiprocessor (SM) on an NVIDIA GPU?",
        choices: [
          "The PCIe interconnect block",
          "A scheduler block containing many CUDA cores, warp schedulers, registers, and shared memory",
          "The video output engine",
          "An on-chip cache only"
        ],
        answer: 1,
        explanation: "An SM is the GPU's basic compute building block. It bundles execution units (CUDA cores, tensor cores, special-function units), warp schedulers, a register file, and shared memory / L1. A modern GPU has dozens to over a hundred SMs working in parallel."
      },
      {
        q: "What are Tensor Cores designed to accelerate?",
        choices: [
          "General double-precision scalar arithmetic",
          "Ray-triangle intersection tests",
          "Small matrix-multiply-and-accumulate operations, often in lower precision (FP16/BF16/FP8/INT8)",
          "Memory copies between host and device"
        ],
        answer: 2,
        explanation: "Tensor Cores (introduced in Volta, 2017) execute small matrix-multiply-accumulate (MMA) operations as one instruction, primarily in reduced precision. They are the workhorses behind modern deep-learning throughput, often offering 5–20× the FLOPs of regular CUDA cores for matmul."
      },
      {
        q: "What is 'warp divergence' and why does it hurt performance?",
        choices: [
          "When two GPUs in NVLink fall out of sync — fixed by NVLink topology tools",
          "When threads in the same warp take different branches and the warp must serialize each branch path, idling other lanes",
          "When the GPU clock drifts from the CPU clock, causing missed frames",
          "When PCIe DMA transfers are reordered"
        ],
        answer: 1,
        explanation: "Because a warp shares one program counter, if its 32 threads take different branches the hardware executes each path with the non-participating lanes masked off. The cost scales with the number of distinct paths, so data-dependent branching inside a warp is a classic GPU performance pitfall."
      },
      {
        q: "Why does GPU memory bandwidth (e.g., HBM3) matter so much for deep-learning workloads?",
        choices: [
          "Because deep learning runs entirely from disk",
          "Many DL kernels are memory-bandwidth bound — feeding tensor cores fast enough requires very high off-chip bandwidth",
          "Because GPUs cannot cache anything",
          "Because PCIe bandwidth is unlimited so HBM is irrelevant"
        ],
        answer: 1,
        explanation: "Modern accelerators have so much compute that many real workloads are limited by how fast data can be moved into the chip — not by FLOPs. HBM (High-Bandwidth Memory) stacks DRAM dies next to the GPU die over a wide interface, delivering TB/s of bandwidth that GDDR can't match."
      }
    ]
  },

  cpu_vs_gpu: {
    title: "CPU vs. GPU",
    icon: "C",
    description: "Latency vs. throughput, control flow vs. data parallelism.",
    questions: [
      {
        q: "Which one-line summary best captures the architectural difference between CPUs and GPUs?",
        choices: [
          "CPUs are analog; GPUs are digital",
          "CPUs are latency-optimized with few powerful cores; GPUs are throughput-optimized with many simpler cores",
          "GPUs run only graphics; CPUs run only general code",
          "CPUs are 64-bit; GPUs are 32-bit"
        ],
        answer: 1,
        explanation: "A CPU dedicates lots of transistors to making a single thread fast: deep pipelines, big caches, branch prediction, out-of-order execution. A GPU dedicates transistors to running thousands of simpler threads in parallel — sacrificing single-thread latency for aggregate throughput."
      },
      {
        q: "Which feature is far more developed on a CPU than on a GPU?",
        choices: [
          "High aggregate floating-point throughput",
          "Sophisticated per-core branch prediction and out-of-order execution",
          "Wide SIMD-style execution across thousands of lanes",
          "On-chip HBM memory"
        ],
        answer: 1,
        explanation: "CPUs put enormous die area into making sequential code fast: branch predictors, large reorder buffers, speculative execution, deep cache hierarchies. GPUs largely skip this complexity per core and instead hide latency by switching to other ready warps."
      },
      {
        q: "Which workload is best suited to a GPU?",
        choices: [
          "A small recursive parser with heavy data-dependent branching",
          "A 16-core build of a C++ project",
          "Multiplying two 8192×8192 matrices with millions of independent multiply-adds",
          "Booting an operating system"
        ],
        answer: 2,
        explanation: "GPUs shine on workloads that are massively data-parallel, regular, and arithmetic-heavy — exactly like dense linear algebra, image filters, and physics simulations. Code with heavy serial dependencies or unpredictable branches stays on the CPU."
      },
      {
        q: "How do CPUs and GPUs differ in how they hide memory latency?",
        choices: [
          "CPUs ignore memory latency entirely",
          "CPUs rely on big caches, prefetchers, and out-of-order execution; GPUs rely on massive thread-level parallelism, swapping in other ready warps when one stalls",
          "GPUs use no caches, only registers",
          "Both rely solely on prefetchers"
        ],
        answer: 1,
        explanation: "The CPU strategy is to keep one thread fast: deep caches, prefetching, OOO. The GPU strategy is the opposite: when a warp stalls on memory, the SM instantly switches to another ready warp. With thousands of in-flight threads, latency is amortized across them."
      },
      {
        q: "Which statement about cache sizes is most accurate?",
        choices: [
          "GPUs typically have larger per-core caches than CPUs",
          "CPUs have much larger per-core caches; GPU caches are smaller per thread but feed thousands of threads",
          "Neither CPUs nor GPUs use caches",
          "GPU L2 caches are always bigger than CPU L3 caches"
        ],
        answer: 1,
        explanation: "Server CPUs often have tens of MB of L3 per core's reach. GPUs have proportionally less cache per thread because they are not trying to keep one thread fast — they're keeping thousands of threads fed, mostly via high-bandwidth memory and software-managed shared memory."
      },
      {
        q: "Why are GPUs so dominant for deep-learning training?",
        choices: [
          "Because neural networks require an OS",
          "Because matmul-heavy workloads map naturally to thousands of parallel multiply-accumulate units, and tensor cores accelerate the dominant kernels further",
          "Because CPUs cannot do floating-point math",
          "Because GPUs have higher clock speeds than CPUs"
        ],
        answer: 1,
        explanation: "Training is dominated by large dense matrix multiplications and convolutions — embarrassingly data-parallel and arithmetic-intensive. GPUs offer one to two orders of magnitude more relevant FLOPs and bandwidth than CPUs, and tensor cores extend that lead in low precision."
      },
      {
        q: "Which is a typical reason to keep a workload on the CPU rather than offload to a GPU?",
        choices: [
          "The workload is small or highly serial, and PCIe transfer overhead would dominate any speedup",
          "GPUs cannot do integer arithmetic",
          "GPUs cannot run code written in C",
          "CPUs are always faster"
        ],
        answer: 0,
        explanation: "Moving data over PCIe and launching a kernel has measurable overhead. For small, latency-sensitive, or serial tasks the round trip eats any compute advantage. Heuristic: GPUs win when the data is big and the work per byte is high."
      }
    ]
  },

  evolution: {
    title: "Evolution of GPUs",
    icon: "E",
    description: "From fixed-function graphics pipelines to programmable AI accelerators.",
    questions: [
      {
        q: "What were early GPUs (late 1990s, e.g., NVIDIA RIVA / GeForce 256) primarily designed to do?",
        choices: [
          "Train neural networks",
          "Accelerate fixed-function 3D graphics pipelines — transform, lighting, and rasterization",
          "Mine cryptocurrency",
          "Run general-purpose C code"
        ],
        answer: 1,
        explanation: "The original GPUs offloaded the fixed-function 3D graphics pipeline — vertex transform & lighting (T&L), rasterization, texture mapping — from the CPU. NVIDIA marketed the GeForce 256 (1999) as 'the world's first GPU' because it integrated T&L on the chip."
      },
      {
        q: "What major shift did programmable shaders (early 2000s, e.g., GeForce 3, DirectX 8) introduce?",
        choices: [
          "GPUs gained their own operating system",
          "Parts of the pipeline (vertex and pixel processing) became programmable, enabling custom per-vertex/per-pixel code",
          "GPUs stopped supporting 3D graphics",
          "GPUs moved off the PCIe bus"
        ],
        answer: 1,
        explanation: "Programmable vertex and pixel shaders replaced fixed-function stages with small programs. This is the foundation everything else built on — once you can run arbitrary code per-pixel, the GPU is on its way to becoming a general parallel processor."
      },
      {
        q: "Which 2006 release made GPUs broadly usable for general-purpose computation?",
        choices: [
          "AMD's Radeon HD 2900",
          "NVIDIA's G80 / GeForce 8800 with the launch of CUDA",
          "Intel's Larrabee",
          "Apple's Metal API"
        ],
        answer: 1,
        explanation: "NVIDIA's G80 (2006) introduced a unified shader architecture and shipped alongside CUDA, a C-like programming model for general computation on the GPU. It turned GPUs from graphics-only chips into general parallel processors and kicked off the GPGPU era."
      },
      {
        q: "Which moment is widely credited with sparking the modern deep-learning boom on GPUs?",
        choices: [
          "Quake III being released in 1999",
          "AlexNet winning ImageNet 2012, trained on two NVIDIA GTX 580 GPUs",
          "The launch of OpenGL 1.0",
          "The release of Windows Vista"
        ],
        answer: 1,
        explanation: "Krizhevsky, Sutskever, and Hinton's AlexNet (2012) cut ImageNet error dramatically and was trained on consumer GPUs. It demonstrated that GPU-accelerated deep learning was practical and effective, triggering the modern surge in DL research and GPU demand."
      },
      {
        q: "Which NVIDIA architecture introduced Tensor Cores for accelerating mixed-precision matrix math?",
        choices: ["Kepler (2012)", "Maxwell (2014)", "Pascal (2016)", "Volta (2017)"],
        answer: 3,
        explanation: "Volta (V100, 2017) was the first NVIDIA architecture with Tensor Cores. They've been a centerpiece of every datacenter generation since: Turing, Ampere (A100), Hopper (H100, with FP8), and Blackwell (B100/B200)."
      },
      {
        q: "Which architecture introduced dedicated RT (ray-tracing) cores for real-time ray-triangle intersection?",
        choices: ["Pascal", "Volta", "Turing (2018)", "Ampere"],
        answer: 2,
        explanation: "Turing (RTX 20-series, 2018) added RT cores for hardware-accelerated BVH traversal and ray-triangle tests, enabling real-time ray tracing in games. Turing also brought tensor cores to consumer GPUs, powering DLSS."
      },
      {
        q: "What does HBM (High-Bandwidth Memory) provide that GDDR does not, and why does it matter for AI GPUs?",
        choices: [
          "HBM is cheaper per GB than GDDR",
          "HBM stacks DRAM dies and uses a very wide interface for far higher bandwidth, which is critical for memory-bound DL workloads",
          "HBM stores data on disk for persistence",
          "HBM is non-volatile"
        ],
        answer: 1,
        explanation: "HBM places stacked DRAM next to the GPU on a silicon interposer, with a much wider interface than GDDR. The result is dramatically higher bandwidth (TB/s), at higher cost. Datacenter AI GPUs (P100/V100/A100/H100/B200, MI200/MI300) all use HBM because DL is bandwidth-hungry."
      },
      {
        q: "Roughly, what is the chronological order of these recent NVIDIA datacenter architectures?",
        choices: [
          "Hopper → Ampere → Volta → Blackwell",
          "Volta (2017) → Ampere (2020) → Hopper (2022) → Blackwell (2024)",
          "Ampere → Volta → Blackwell → Hopper",
          "Blackwell → Hopper → Volta → Ampere"
        ],
        answer: 1,
        explanation: "The datacenter line ran Volta (V100) → Turing (T4) → Ampere (A100) → Hopper (H100, with FP8 and the Transformer Engine) → Blackwell (B100/B200, ~2024). Each generation pushed tensor throughput, memory bandwidth, and interconnect (NVLink/NVSwitch) for ever-larger models."
      },
      {
        q: "Which trend has most defined GPU evolution since ~2017?",
        choices: [
          "A return to fixed-function graphics-only pipelines",
          "Specialization for AI: tensor cores, lower-precision formats (FP16/BF16/FP8), HBM, fast interconnects, and multi-GPU scale-out",
          "Dropping floating-point support",
          "Moving entirely off PCIe to USB"
        ],
        answer: 1,
        explanation: "Modern GPU roadmaps are increasingly shaped by AI workloads: tensor/matrix engines, ever-lower precision (FP16 → BF16 → FP8 → FP4), HBM stacks for bandwidth, NVLink/NVSwitch for tight multi-GPU coupling, and rack-scale systems (DGX/HGX, GB200 NVL72) optimized for training and serving large models."
      }
    ]
  }
};

const COLLECTIONS = {
  llms: {
    title: "LLMs",
    description: "Each quiz has multiple-choice questions with explanations after every answer.",
    quizzes: LLM_QUIZZES,
    topicOrder: ["generic", "instruction", "dialogue", "domain", "evolution"]
  },
  gpus: {
    title: "GPUs",
    description: "Architecture, how GPUs differ from CPUs, and how they evolved into AI accelerators.",
    quizzes: GPU_QUIZZES,
    topicOrder: ["architecture", "cpu_vs_gpu", "evolution"]
  }
};

const COLLECTION_ORDER = ["llms", "gpus"];

const state = {
  currentCollection: "llms",
  currentTopic: null,
  currentIndex: 0,
  score: 0,
  answered: false
};

function getQuiz(topicKey) {
  return COLLECTIONS[state.currentCollection].quizzes[topicKey];
}

const $ = (id) => document.getElementById(id);

function showScreen(name) {
  document.querySelectorAll(".screen").forEach((s) => s.classList.remove("active"));
  $(name).classList.add("active");
}

function renderCollectionTabs() {
  const tabs = $("collection-tabs");
  tabs.innerHTML = "";
  for (const key of COLLECTION_ORDER) {
    const c = COLLECTIONS[key];
    const btn = document.createElement("button");
    btn.className = "collection-tab" + (key === state.currentCollection ? " active" : "");
    btn.textContent = c.title;
    btn.setAttribute("role", "tab");
    btn.addEventListener("click", () => {
      if (state.currentCollection === key) return;
      state.currentCollection = key;
      renderCollectionTabs();
      renderTopics();
    });
    tabs.appendChild(btn);
  }
  const c = COLLECTIONS[state.currentCollection];
  $("collection-desc").textContent = c.description;
}

function renderTopics() {
  const collection = COLLECTIONS[state.currentCollection];
  const grid = $("topic-grid");
  grid.innerHTML = "";
  for (const key of collection.topicOrder) {
    const quiz = collection.quizzes[key];
    const card = document.createElement("button");
    card.className = "topic-card";
    card.innerHTML = `
      <span class="topic-icon">${quiz.icon}</span>
      <h3>${quiz.title}</h3>
      <p>${quiz.description}</p>
      <span class="topic-count">${quiz.questions.length} questions</span>
    `;
    card.addEventListener("click", () => startQuiz(key));
    grid.appendChild(card);
  }
}

function startQuiz(topicKey) {
  state.currentTopic = topicKey;
  state.currentIndex = 0;
  state.score = 0;
  state.answered = false;
  $("quiz-title").textContent = getQuiz(topicKey).title;
  $("score").textContent = "0";
  showScreen("quiz");
  renderQuestion();
}

function renderQuestion() {
  const quiz = getQuiz(state.currentTopic);
  const qIdx = state.currentIndex;
  const question = quiz.questions[qIdx];
  state.answered = false;

  $("progress-text").textContent = `Question ${qIdx + 1} of ${quiz.questions.length}`;
  $("progress-fill").style.width = `${(qIdx / quiz.questions.length) * 100}%`;
  $("question-text").textContent = question.q;

  const choices = $("choices");
  choices.innerHTML = "";
  const letters = ["A", "B", "C", "D", "E", "F"];
  question.choices.forEach((text, i) => {
    const li = document.createElement("li");
    li.className = "choice";
    li.innerHTML = `<span class="letter">${letters[i]}</span><span>${text}</span>`;
    li.addEventListener("click", () => selectChoice(i));
    choices.appendChild(li);
  });

  const explanation = $("explanation");
  explanation.classList.add("hidden");
  explanation.classList.remove("correct", "incorrect");
  $("next-btn").classList.add("hidden");
}

function selectChoice(idx) {
  if (state.answered) return;
  state.answered = true;

  const quiz = getQuiz(state.currentTopic);
  const question = quiz.questions[state.currentIndex];
  const correctIdx = question.answer;
  const isCorrect = idx === correctIdx;

  if (isCorrect) state.score += 1;
  $("score").textContent = String(state.score);

  const items = document.querySelectorAll("#choices .choice");
  items.forEach((el, i) => {
    el.classList.add("locked");
    if (i === correctIdx) el.classList.add("correct");
    else if (i === idx) el.classList.add("incorrect");
    else el.classList.add("dimmed");
  });

  const explanation = $("explanation");
  explanation.classList.remove("hidden");
  explanation.classList.add(isCorrect ? "correct" : "incorrect");
  $("explanation-title").textContent = isCorrect ? "Correct!" : "Not quite.";
  $("explanation-text").textContent = question.explanation;

  const isLast = state.currentIndex === quiz.questions.length - 1;
  const nextBtn = $("next-btn");
  nextBtn.textContent = isLast ? "See Results →" : "Next Question →";
  nextBtn.classList.remove("hidden");
}

function nextQuestion() {
  const quiz = getQuiz(state.currentTopic);
  if (state.currentIndex < quiz.questions.length - 1) {
    state.currentIndex += 1;
    renderQuestion();
    window.scrollTo({ top: 0, behavior: "smooth" });
  } else {
    showResults();
  }
}

function showResults() {
  const quiz = getQuiz(state.currentTopic);
  $("final-score").textContent = String(state.score);
  $("final-total").textContent = String(quiz.questions.length);
  const pct = state.score / quiz.questions.length;
  let msg;
  if (pct === 1) msg = "Perfect score — nailed it!";
  else if (pct >= 0.8) msg = "Excellent work. Solid grasp of the material.";
  else if (pct >= 0.6) msg = "Good effort — review the explanations and try again.";
  else if (pct >= 0.4) msg = "Some gaps to fill. The explanations are a great place to start.";
  else msg = "Plenty to learn here — read the explanations and give it another go.";
  $("result-message").textContent = msg;
  showScreen("results");
}

function init() {
  renderCollectionTabs();
  renderTopics();

  $("back-home").addEventListener("click", () => showScreen("home"));
  $("home-btn").addEventListener("click", () => showScreen("home"));
  $("retry-btn").addEventListener("click", () => startQuiz(state.currentTopic));
  $("next-btn").addEventListener("click", nextQuestion);
}

document.addEventListener("DOMContentLoaded", init);
