registerQuiz({
  collection: "llms",
  key: "generic",
  title: "Generic Language Models",
  icon: "G",
  description: "Foundation models trained on broad text to predict the next token.",
  questions: [
    {
      q: "What is the core training objective of a generic (pretrained) large language model?",
      choices: [
        "Maximize a human-rating score from labelers",
        "Predict the next token given the previous tokens",
        "Classify text into predefined categories",
        "Translate text between two specified languages"
      ],
      answer: 1,
      explanation: "Generic LLMs are trained with self-supervised next-token prediction on huge corpora. No human labels or task-specific heads are needed — the model just learns to continue text, which implicitly forces it to learn grammar, facts, and reasoning patterns."
    },
    {
      q: "Why are generic LLMs sometimes called 'foundation models'?",
      choices: [
        "They run only on foundational hardware like CPUs",
        "They form a general-purpose base that can be adapted to many downstream tasks",
        "They were the first models ever built",
        "They are limited to one foundational task such as translation"
      ],
      answer: 1,
      explanation: "Coined by Stanford's CRFM in 2021, 'foundation model' captures the idea that one large pretrained model serves as a base that can be fine-tuned, prompted, or adapted to a wide variety of tasks — rather than training a separate model from scratch for each task."
    },
    {
      q: "If you ask a purely generic (not instruction-tuned) language model 'What is the capital of France?', what is the most likely behavior?",
      choices: [
        "It refuses because it is not allowed to answer questions",
        "It answers concisely with 'Paris.'",
        "It may continue the text — e.g., generate more questions or a quiz-like list rather than directly answering",
        "It returns an error because the prompt is not well-formed"
      ],
      answer: 2,
      explanation: "A pure pretrained LLM is just a text continuator. Without instruction tuning, it has no special bias to 'follow' a question — it predicts what text typically follows. Often this means continuing in the same style, e.g., listing more trivia questions, rather than answering directly."
    },
    {
      q: "Which of the following is NOT typically a property of generic pretrained LLMs?",
      choices: [
        "Trained with self-supervised learning on unlabeled text",
        "Capable of few-shot in-context learning",
        "Aligned by default to be helpful, harmless, and honest",
        "Knowledge is bounded by their training cutoff"
      ],
      answer: 2,
      explanation: "Alignment (helpful/harmless/honest) is added on top of pretraining via instruction tuning and RLHF/RLAIF. A purely pretrained model has no built-in notion of being helpful — that property comes from later post-training stages."
    },
    {
      q: "Which dataset characteristic is most typical for pretraining a generic LLM?",
      choices: [
        "A small, hand-curated dataset of question/answer pairs",
        "A massive, diverse corpus of unlabeled text from the web, books, and code",
        "A labeled dataset of dialogues with human ratings",
        "Synthetic data generated by another aligned model"
      ],
      answer: 1,
      explanation: "Pretraining relies on scale and diversity — trillions of tokens drawn from web crawls, books, code, and other sources. The text is unlabeled; the next-token target comes for free from the data itself."
    }
  ]
});
