registerQuiz({
  collection: "llms",
  key: "generic",
  title: "Generic Language Models",
  icon: "G",
  description: "Foundation models trained on broad text to predict the next token.",
  createdAt: "2026-04-25T18:00:00Z",
  updatedAt: "2026-06-06T00:35:00Z",
  questions: [
    {
      q: "What is the core training objective of a generic (pretrained) large language model?",
      choices: [
        "Maximize a human-rating score from labelers on response quality",
        "Predict the next token given the previous tokens in the sequence",
        "Classify input text into one of several predefined categories",
        "Translate text between two specified source and target languages"
      ],
      answer: 1,
      explanation: "Generic LLMs are trained with self-supervised next-token prediction on huge corpora. No human labels or task-specific heads are needed — the model just learns to continue text, which implicitly forces it to learn grammar, facts, and reasoning patterns."
    },
    {
      q: "Why are generic LLMs sometimes called 'foundation models'?",
      choices: [
        "They serve as a general-purpose base that can be adapted to many downstream tasks",
        "They were the first language models ever built and are kept for legacy reasons",
        "They run only on a foundational class of dedicated AI accelerator hardware",
        "They are constrained to a single foundational task such as machine translation"
      ],
      answer: 0,
      explanation: "Coined by Stanford's CRFM in 2021, 'foundation model' captures the idea that one large pretrained model serves as a base that can be fine-tuned, prompted, or adapted to a wide variety of tasks — rather than training a separate model from scratch for each task."
    },
    {
      q: "If you ask a purely generic (not instruction-tuned) language model 'What is the capital of France?', what is the most likely behavior?",
      choices: [
        "It refuses because it has not been authorized to answer factual questions",
        "It produces 'Paris.' as cleanly as an instruction-tuned chat model would",
        "It returns an explicit error because the prompt does not match its expected format",
        "It often continues the text — e.g., generating more questions in the same style"
      ],
      answer: 3,
      explanation: "A pure pretrained LLM is just a text continuator. Without instruction tuning, it has no special bias to 'follow' a question — it predicts what text typically follows. Often this means continuing in the same style, e.g., listing more trivia questions, rather than answering directly."
    },
    {
      q: "Which of the following is NOT typically a property of generic pretrained LLMs?",
      choices: [
        "Trained with self-supervised learning on large amounts of unlabeled text",
        "Capable of few-shot in-context learning when given examples in the prompt",
        "Aligned by default to be helpful, harmless, and honest in their replies",
        "Have a knowledge horizon bounded by the cutoff of their training data"
      ],
      answer: 2,
      explanation: "Alignment (helpful/harmless/honest) is added on top of pretraining via instruction tuning and RLHF/RLAIF. A purely pretrained model has no built-in notion of being helpful — that property comes from later post-training stages."
    },
    {
      q: "Which dataset characteristic is most typical for pretraining a generic LLM?",
      choices: [
        "A small, hand-curated dataset of high-quality question-and-answer pairs",
        "A large labeled dataset of dialogues with detailed human preference ratings",
        "Synthetic instruction data generated by another aligned, instruction-tuned model",
        "A massive corpus of unlabeled text drawn from the web, books, papers, and code"
      ],
      answer: 3,
      explanation: "Pretraining relies on scale and diversity — trillions of tokens drawn from web crawls, books, code, and other sources. The text is unlabeled; the next-token target comes for free from the data itself."
    }
  ]
});
